# Generated by Django 4.1.5 on 2023-01-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("filesupload", "0002_transactions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transactions",
            old_name="cartão",
            new_name="cartao",
        ),
    ]
