# Generated by Django 4.1.5 on 2023-01-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("filesupload", "0003_rename_cartão_transactions_cartao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="tipo",
            field=models.CharField(max_length=30),
        ),
    ]
